/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_The_Zycus_HeraldTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_The_Zycus_HeraldTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new The_Zycus_Herald__c());
    }
}