/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_Competitive_Win_Loss_AnalysisTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_Competitive_Win_Loss_Anala6DTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new Competitive_Win_Loss_Analysis__c());
    }
}