/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_bombora_data_Bombora_Companya79Test
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_bombora_data_Bombora_Compa79Trigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new bombora_data__Bombora_Company_Surge__c());
    }
}