/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_DOZISF_ZoomInfo_IntentTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_DOZISF_ZoomInfo_IntentTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new DOZISF__ZoomInfo_Intent__c());
    }
}